name: Auto Update

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          cd data
          today=$(date +'%-d.%-m.%Y')
          wget "https://covid19-dashboard.ages.at/data/CovidFaelle_GKZ.csv" -O rawdata_${today}.csv --ciphers 'DEFAULT:!DH'
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Data ${today}"
          git push
          echo "PATH=data/rawdata_${today}.csv" >> $GITHUB_OUTPUT
        id: download
      - uses: noahreinalter/regex-match-file@latest
        with:
          regex_pattern: '(Bezirk;GKZ;AnzEinwohner;Anzahl;AnzahlTot;AnzahlFaelle7Tage)(\n.*(;\d+){5}){94}'
          path: ${{ steps.download.outputs.PATH }}
